Refactor yaml format
tud-cs/oss-collection pull request #2
Opened 2024-09-11 05:54 UTC by PaulPickhardt

Splits project yaml in oss-projects and cs-groups and refactors the yaml keys.

Closes #1

2024-09-11 07:28 UTC, PaulPickhardt commented
I'm done with refactoring the Yaml files as supposed in issue #1. I changed `chair` to `groups` in `oss-projects.yaml`. 

Let me know what you think @waehlisch @adeveloper-wq

2024-09-16 10:41 UTC, waehlisch requested changes
in addition to what we just talked about.

2024-09-16 10:41 UTC, waehlisch commented on README-template.md
>  # TU Dresden - Computer Science: Open Source Projects
Open Source Projects of the Faculty of Computer Science at TU Dresden

2024-09-16 10:41 UTC, waehlisch commented on README-template.md
> +This repository contains functionality to generate a HTML and markdown site of all projects entered in `oss-projects.yaml` and computer science groups in `cs-groups.yaml`.
This repository contains scripts and data to generate HTML and markdown files presenting open source software projects of the [Faculty of Computer Science](https://cs.tu-dresden.de) at [TU Dresden](https://www.tu-dresden.de). The sources of information are `oss-projects.yaml`, which describes the projects, and `cs-groups.yaml`, which describes the research groups involved.

2024-09-16 10:41 UTC, waehlisch commented on README-template.md
> +For the groups add the handle of your computer science group to the list.
For the groups, add the handle of your research group to the list.

2024-09-16 10:41 UTC, waehlisch commented on README-template.md
> +If your computer science group does not exist yet, append this template to `cs-groups.yaml` and fill in your data:
If your research group [...]

2024-09-16 10:51 UTC, waehlisch commented on README.md
>  # Projects
Paragraph below: The following list presents open source software projects in which members of the Faculty of Computer Science at TU Dresden are involved.

2024-09-16 11:58 UTC, PaulPickhardt commented
The description is now optional and I added your suggestions to the readme @waehlisch

2024-09-17 06:01 UTC, waehlisch approved these changes

2024-09-17 06:02 UTC, merged